export default {
    SUCCESS: 'The operation has been successful',
    CREATED: 'The resource has been created successfully',
    UPDATED: 'The resource has been updated successfully',
    DELETED: 'The resource has been deleted successfully',

    SERVICE: (service) => `${service} service is running.`,

    ERROR: {
        SOMETHING_WENT_WRONG: 'Something went wrong!',
        INTERNAL_SERVER_ERROR: 'Internal server error',
        NOT_FOUND: (entity) => `${entity} not found`,
        ALREADY_EXISTS: (entity) => `${entity} already exists`,
        TOO_MANY_REQUESTS: 'Too many requests! Please try again after some time',
        BAD_REQUEST: 'Bad request',
        DATABASE_ERROR: 'A database error occurred',
        SERVICE_UNAVAILABLE: 'Service temporarily unavailable',
        DUPLICATE_ENTRY: (field) => `Duplicate entry for ${field}`,
        INVALID_OPERATION: 'Invalid operation requested'
    },
    COMMON: {
        INVALID_PARAMETERS: (param) => (param ? `Invalid parameter: ${param}` : 'Invalid parameters provided'),
        ACTION_NOT_ALLOWED: 'This action is not allowed',
        OPERATION_FAILED: (operation) => `${operation} operation failed`,
        OPERATION_SUCCESS: (operation) => `${operation} operation succeeded`,
        FAILED_TO_SAVE: (entity) => `Failed to save ${entity}`,
        INVALID_ID: 'Invalid ID format provided',
        FAILED_TO_UPDATE: (entity) => `Failed to update ${entity}`,
        PAGINATION_INVALID: 'Invalid pagination parameters',
        SORT_INVALID: 'Invalid sort parameters',
        FILTER_INVALID: 'Invalid filter parameters'
    },
    AUTH: {
        LOGIN_SUCCESS: 'Login successful',
        LOGIN_FAILED: 'Invalid email or password',
        UNAUTHORIZED: 'You are not authorized to access this resource',
        FORBIDDEN: 'You do not have permission to perform this action',
        TOKEN_EXPIRED: 'Authentication token has expired',
        TOKEN_INVALID: 'Authentication token is invalid',
        ALREADY_EXIST: (entity, value) => `${entity} with value ${value} already exists`,
        INVALID_PHONE_NUMBER: 'Invalid phone number provided',
        ACCOUNT_ALREADY_CONFIRMED: 'Account already confirmed',
        ACCOUNT_NOT_CONFIRMED: 'Account not confirmed',
        PASSWORD_NOT_MATCH: 'Password does not match',
        INVALID_PASSWORD: 'Invalid password provided',
        PASSWORD_RESET_SUCCESS: 'Password reset successful',
        PASSWORD_RESET_FAILED: 'Password reset failed',
        PASSWORD_RESET_TOKEN_EXPIRED: 'Password reset token has expired',
        ACCOUNT_CONFIRMED: 'Account confirmed successfully',
        ACCOUNT_DEACTIVATED: 'Account is deactivated'
    },
    SELLER: {
        PROFILE_CREATED: 'Seller profile created successfully and submitted for review',
        PROFILE_ALREADY_EXISTS: 'You already have a seller profile',
        PROFILE_SUBMITTED: 'Profile submitted for verification successfully',
        PROFILE_ALREADY_SUBMITTED: 'Profile has already been submitted for review',
        PROFILE_NOT_ACTIVE: 'Seller profile is not active or approved',
        INCOMPLETE_PROFILE: 'Please complete your profile before submitting for verification (minimum 80% completion required)',
        CANNOT_UPDATE_APPROVED_PROFILE: 'Cannot update profile once it has been approved. Contact support for changes.',

        COMMISSION_OFFERED: 'Commission offer sent to seller successfully',
        COMMISSION_ACCEPTED: 'Commission offer accepted successfully. Welcome to our seller community!',
        COMMISSION_REJECTED: 'Commission offer rejected',
        COMMISSION_ALREADY_RESPONDED: 'You have already responded to this commission offer',
        NO_COMMISSION_OFFER: 'No pending commission offer found',
        COUNTER_OFFER_SUBMITTED: 'Counter offer submitted successfully',

        CANNOT_OFFER_COMMISSION: 'Can only offer commission to profiles under review or respond to counter offers',
        CANNOT_REJECT_PROFILE: 'Can only reject profiles that are under review or in commission negotiation',
        PROFILE_REJECTED: 'Seller profile has been rejected',
        MAX_NEGOTIATION_ROUNDS_REACHED: 'Maximum negotiation rounds (5) reached. Please contact support for further assistance.',

        PAYOUT_INFO_UPDATED: 'Payout information updated successfully',
        PAYOUT_INFO_INVALID: 'Invalid payout information provided',
        PAYOUT_VERIFICATION_PENDING: 'Payout information is pending verification',
        PAYOUT_VERIFIED: 'Payout information verified successfully',

        STATS_UPDATED: 'Seller statistics updated successfully',
        INVALID_RATING: 'Rating must be between 1 and 5',

        PROFILE_COMPLETION_LOW: 'Profile completion is below required threshold',
        REQUIRED_FIELDS_MISSING: 'Please fill in all required fields',

        NO_SELLERS_FOUND: 'No sellers found matching your criteria',
        SEARCH_RESULTS_FOUND: (count) => `Found ${count} sellers matching your criteria`,
        COUNTER_OFFER_ACCEPTED: 'Counter offer accepted successfully',
        NO_COUNTER_OFFER: 'No pending counter offer found',
        
        SUSPENDED: 'Seller account suspended successfully',
        ACTIVATED: 'Seller account activated successfully',
        ALREADY_SUSPENDED: 'Seller account is already suspended',
        ALREADY_ACTIVE: 'Seller account is already active',
        NOT_APPROVED_FOR_ACTIVATION: 'Seller must be approved before activation'
    },

    PRODUCT: {
        CREATED: 'Product created successfully',
        UPDATED: 'Product updated successfully',
        DELETED: 'Product deleted successfully',
        PUBLISHED: 'Product published successfully',
        ARCHIVED: 'Product archived successfully',
        SUBMITTED_FOR_REVIEW: 'Product submitted for review successfully',
        NOT_FOUND: 'Product not found',
        ALREADY_EXISTS: 'Product with this title already exists',
        INVALID_STATUS: 'Invalid product status',
        UNAUTHORIZED_ACCESS: 'You are not authorized to access this product',
        CANNOT_REVIEW_OWN_PRODUCT: 'You cannot review your own product',
        ALREADY_REVIEWED: 'You have already reviewed this product',
        REVIEW_ADDED: 'Review added successfully',
        REVIEW_UPDATED: 'Review updated successfully',
        REVIEW_DELETED: 'Review deleted successfully',
        FAVORITE_ADDED: 'Product added to favorites',
        FAVORITE_REMOVED: 'Product removed from favorites',
        UPVOTE_ADDED: 'Product upvoted successfully',
        UPVOTE_REMOVED: 'Product upvote removed successfully',
        VERIFICATION_UPDATED: 'Product verification status updated',
        SLUG_ALREADY_EXISTS: 'Product with this slug already exists',
        INVALID_PRICE: 'Invalid price provided',
        INVALID_RATING: 'Rating must be between 1 and 5',
        INVALID_SORT_FIELD: 'Invalid sort field provided',
        INVALID_FILTER: 'Invalid filter parameters',
        NO_PRODUCTS_FOUND: 'No products found matching your criteria',
        SEARCH_RESULTS_FOUND: (count) => `Found ${count} products matching your criteria`,
        RELATED_PRODUCTS_FOUND: (count) => `Found ${count} related products`,
        SELLER_PRODUCTS_FOUND: (count) => `Found ${count} products from this seller`,
        MINIMUM_PRICE_REQUIRED: 'Minimum price is required for paid products',
        INVALID_SETUP_TIME: 'Invalid setup time provided',
        INVALID_CATEGORY: 'Invalid product category',
        INVALID_TYPE: 'Invalid product type',
        INVALID_INDUSTRY: 'Invalid industry',
        TOOLS_REQUIRED: 'At least one tool is required',
        DESCRIPTION_TOO_SHORT: 'Description must be at least 50 characters',
        TITLE_TOO_LONG: 'Title must be less than 100 characters',
        TAGS_LIMIT_EXCEEDED: 'Maximum 10 tags allowed',
        IMAGES_LIMIT_EXCEEDED: 'Maximum 10 images allowed',
        FAQS_LIMIT_EXCEEDED: 'Maximum 20 FAQs allowed',
        VERSIONS_LIMIT_EXCEEDED: 'Maximum 50 versions allowed',
        BULK_OPERATION_SUCCESS: (count, operation) => `${count} products ${operation} successfully`,
        BULK_OPERATION_FAILED: (operation) => `Bulk ${operation} operation failed`,
        PRODUCT_NOT_PUBLISHED: 'Product is not published',
        PRODUCT_ARCHIVED: 'Product is archived and cannot be accessed',
        SIMILAR_PRODUCTS_FOUND: (count) => `Found ${count} similar products`,
        CANNOT_UPDATE_PURCHASED_PRODUCT: 'Cannot update product that has been purchased by users. Contact admin if changes are necessary.',
        
        // Purchase related messages
        PURCHASE_SUCCESSFUL: 'Product purchased successfully',
        ALREADY_PURCHASED: 'You have already purchased this product',
        CANNOT_PURCHASE_OWN_PRODUCT: 'You cannot purchase your own product',
        CANNOT_ADD_OWN_PRODUCT_TO_CART: 'You cannot add your own product to cart',
        FREE_PRODUCT_ACCESSED: 'Free product access granted successfully',
        ACCESS_DENIED: 'You do not have access to this premium content',
        STATUS_UPDATED: 'Product status updated successfully'
    },

    CART: {
        ITEM_ADDED: 'Product added to cart successfully',
        ITEM_REMOVED: 'Product removed from cart successfully',
        ITEM_ALREADY_IN_CART: 'Product is already in your cart',
        CLEARED: 'Cart cleared successfully',
        EMPTY_CART: 'Your cart is empty',
        NO_VALID_ITEMS: 'No valid items found in cart'
    },

    PROMOCODE: {
        APPLIED: 'Promocode applied successfully',
        REMOVED: 'Promocode removed successfully',
        INVALID: 'Invalid or expired promocode',
        VALID: 'Promocode is valid',
        ALREADY_APPLIED: 'A promocode is already applied',
        MINIMUM_ORDER_NOT_MET: 'Minimum order amount not met for this promocode',
        CREATED: 'Promocode created successfully',
        UPDATED: 'Promocode updated successfully',
        DELETED: 'Promocode deleted successfully',
        ACTIVATED: 'Promocode activated successfully',
        DEACTIVATED: 'Promocode deactivated successfully',
        NOT_FOUND: 'Promocode not found',
        CODE_ALREADY_EXISTS: 'A promocode with this code already exists',
        UNAUTHORIZED_ACCESS: 'You are not authorized to access this promocode',
        CANNOT_MODIFY_USED_PROMOCODE: 'Cannot modify a promocode that has been used',
        CANNOT_DELETE_USED_PROMOCODE: 'Cannot delete a promocode that has been used',
        INVALID_EXPIRY_DATE: 'Expiry date must be in the future',
        GLOBAL_NOT_ALLOWED_FOR_SELLER: 'Sellers cannot create global promocodes',
        NOT_APPLICABLE_TO_PRODUCTS: 'Promocode is not applicable to selected products',
        NOT_APPLICABLE_TO_CATEGORIES: 'Promocode is not applicable to selected product categories'
    },

    customMessage: (message) => message
}

